### ISSUE TITLE
Best technique to set up multiple sites?

### ISSUE THREAD

**Issue by davidneedham** [ataylorme/wordpress-at-scale-auto-update#25]
Most people using this will have more than one website they want to update automatically. What is the best way to set that up with this?

At first, I thought to create a fork for each site we want to run updates on, but GitHub only lets you fork a project once per account. We could use a branch per site, but the site UUID is currently defined in a CircleCI environment variable which carries across all branches. Could that be moved into a file?

Alternatively, does it make more sense to simply clone and spin up a brand new repo? I'd rather it be a fork so that it's easier to pull in updates over time.

Other ideas?

**Comment by stevector** [comment]
I agree that one repo per site is not scalable. Overall, I think this repo is best understood as a proof of concept that shows visual regression autoupdating can be done rather than a fully packaged solution for large volumes of sites.

That being said, I think an easy/direct way scale up a bit is to make the site UUID/name be a variable passed into CircleCI. Or rewrite just a little more and have a preconfigured list of site names in the repo and instead of curling every hour, curl every minute or so to churn through the list.

**Comment by ataylorme** [comment]
Closing this out as the updated CircleCI 2.0 version allows for multiple sites to be updated from one repo and takes advantage of parallel workers.
